In [1]:
import pandas as pd

df = pd.read_parquet("D:\\APCIRA\\data\\processed\\incidents_100k.parquet")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (95477, 41)

Columns:
['label', 'protocol', 'src_port', 'dst_port', 'flow_duration', 'total_fwd_packets', 'total_bwd_packets', 'total_len_fwd', 'total_len_bwd', 'flow_packets_s', 'fwd_packets_s', 'bwd_packets_s', 'fwd_packet_length_mean', 'bwd_packet_length_mean', 'min_packet_length', 'max_packet_length', 'packet_length_mean', 'packet_length_std', 'syn_flag_count', 'ack_flag_count', 'rst_flag_count', 'psh_flag_count', 'fin_flag_count', 'fwd_syn_flags', 'bwd_syn_flags', 'fwd_ack_flags', 'bwd_ack_flags', 'fwd_rst_flags', 'bwd_rst_flags', 'fwd_psh_flags', 'bwd_psh_flags', 'down_up_ratio', 'init_win_bytes_forward', 'init_win_bytes_backward', 'active_mean', 'idle_mean', 'src_ip', 'dst_ip', 'timestamp', 'incident_id', 'incident_text']

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 95477 entries, 0 to 95476
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   label                    95477 non-null  str
 1   protocol                 0 non-null      float64
 2   src_port                 0 non-null      float64
 3   dst_port                 95477 non-null  float64
 4   flow_duration            95477 non-null  float64
 5   total_fwd_packets        95477 non-null  float64
 6   total_bwd_packets        95477 non-null  float64
 7   total_len_fwd            95477 non-null  float64
 8   total_len_bwd            95477 non-null  float64
 9   flow_packets_s           95426 non-null  float64
 10  fwd_packets_s            95477 non-null  float64
 11  bwd_packets_s            95477 non-null  float64
 12  fwd_packet_length_mean   95477 non-null  float64
 13  bwd_packet_length_mean   95477 non-null  float64
 14  min_packet_length        95477 non-null  float64
 15  max_packet_length        95477 non-null  float64
 16  packet_length_mean       95477 non-null  float64
 17  packet_length_std        95477 non-null  float64
 18  syn_flag_count           95477 non-null  float64
 19  ack_flag_count           95477 non-null  float64
 20  rst_flag_count           95477 non-null  float64
 21  psh_flag_count           95477 non-null  float64
 22  fin_flag_count           95477 non-null  float64
 23  fwd_syn_flags            0 non-null      float64
 24  bwd_syn_flags            0 non-null      float64
 25  fwd_ack_flags            0 non-null      float64
 26  bwd_ack_flags            0 non-null      float64
 27  fwd_rst_flags            0 non-null      float64
 28  bwd_rst_flags            0 non-null      float64
 29  fwd_psh_flags            95477 non-null  float64
 30  bwd_psh_flags            95477 non-null  float64
 31  down_up_ratio            95477 non-null  float64
 32  init_win_bytes_forward   95477 non-null  float64
 33  init_win_bytes_backward  95477 non-null  float64
 34  active_mean              95477 non-null  float64
 35  idle_mean                95477 non-null  float64
 36  src_ip                   0 non-null      str
 37  dst_ip                   0 non-null      str
 38  timestamp                0 non-null      str
 39  incident_id              95477 non-null  str
 40  incident_text            95477 non-null  str
dtypes: float64(35), str(6)
memory usage: 101.4 MB

In [3]:
df.head()

,label,protocol,src_port,dst_port,flow_duration,total_fwd_packets,total_bwd_packets,total_len_fwd,total_len_bwd,flow_packets_s,...,down_up_ratio,init_win_bytes_forward,init_win_bytes_backward,active_mean,idle_mean,src_ip,dst_ip,timestamp,incident_id,incident_text
0,BENIGN,NaN,NaN,80.0,452460.0,8.0,11.0,1763.0,12834.0,41.992662,...,1.0,8192.0,1095.0,0.0,0.0,NaN,NaN,NaN,INC-000001,Traffic label: BENIGN. Destination port: 80. F...
1,DDoS,NaN,NaN,80.0,9365755.0,4.0,0.0,24.0,0.0,0.427088,...,0.0,256.0,-1.0,1003.0,9364752.0,NaN,NaN,NaN,INC-000002,Attack: DDoS. Destination port: 80. Flow durat...
2,BENIGN,NaN,NaN,56026.0,58.0,1.0,1.0,0.0,0.0,34482.758620,...,1.0,122.0,33304.0,0.0,0.0,NaN,NaN,NaN,INC-000003,Traffic label: BENIGN. Destination port: 56026...
3,DoS Hulk,NaN,NaN,80.0,99971800.0,6.0,6.0,350.0,11595.0,0.120034,...,1.0,274.0,235.0,985.0,99900000.0,NaN,NaN,NaN,INC-000004,Attack: DoS Hulk. Destination port: 80. Flow d...
4,BENIGN,NaN,NaN,443.0,1840298.0,3.0,3.0,0.0,0.0,3.260342,...,1.0,8192.0,0.0,0.0,0.0,NaN,NaN,NaN,INC-000005,Traffic label: BENIGN. Destination port: 443. ...

In [4]:
df.sample(5)

,label,protocol,src_port,dst_port,flow_duration,total_fwd_packets,total_bwd_packets,total_len_fwd,total_len_bwd,flow_packets_s,...,down_up_ratio,init_win_bytes_forward,init_win_bytes_backward,active_mean,idle_mean,src_ip,dst_ip,timestamp,incident_id,incident_text
81318,DoS Hulk,NaN,NaN,80.0,151547.0,3.0,6.0,359.0,11595.0,59.387517,...,2.0,29200.0,235.0,0.0,0.0,NaN,NaN,NaN,INC-081319,Attack: DoS Hulk. Destination port: 80. Flow d...
58792,DoS Hulk,NaN,NaN,80.0,83239087.0,5.0,7.0,346.0,11595.0,0.144163,...,1.0,0.0,235.0,19974.0,83100000.0,NaN,NaN,NaN,INC-058793,Attack: DoS Hulk. Destination port: 80. Flow d...
9639,DDoS,NaN,NaN,80.0,5452838.0,4.0,0.0,24.0,0.0,0.733563,...,0.0,256.0,-1.0,1983.0,5450855.0,NaN,NaN,NaN,INC-009640,Attack: DDoS. Destination port: 80. Flow durat...
77340,BENIGN,NaN,NaN,80.0,5339740.0,3.0,1.0,0.0,0.0,0.749100,...,0.0,8192.0,14600.0,0.0,0.0,NaN,NaN,NaN,INC-077341,Traffic label: BENIGN. Destination port: 80. F...
29635,FTP-Patator,NaN,NaN,21.0,9343972.0,9.0,15.0,110.0,188.0,2.568501,...,1.0,29200.0,227.0,0.0,0.0,NaN,NaN,NaN,INC-029636,Attack: FTP-Patator. Destination port: 21. Flo...

In [5]:
missing = df.isnull().sum()

print(missing[missing > 0])

protocol          95477
src_port          95477
flow_packets_s       51
fwd_syn_flags     95477
bwd_syn_flags     95477
fwd_ack_flags     95477
bwd_ack_flags     95477
fwd_rst_flags     95477
bwd_rst_flags     95477
src_ip            95477
dst_ip            95477
timestamp         95477
dtype: int64

In [6]:
missing_pct = (df.isnull().sum() / len(df)) * 100

print(
    missing_pct[missing_pct > 0]
    .sort_values(ascending=False)
)

protocol          100.000000
src_port          100.000000
fwd_syn_flags     100.000000
bwd_syn_flags     100.000000
bwd_rst_flags     100.000000
fwd_ack_flags     100.000000
bwd_ack_flags     100.000000
fwd_rst_flags     100.000000
dst_ip            100.000000
src_ip            100.000000
timestamp         100.000000
flow_packets_s      0.053416
dtype: float64

In [7]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [8]:
print(df["label"].value_counts())

label
BENIGN              52330
DoS Hulk             7847
DDoS                 7748
PortScan             7643
DoS GoldenEye        5236
FTP-Patator          4259
SSH-Patator          3149
DoS Slowhttptest     2645
DoS slowloris        2637
Bot                  1936
Infiltration           36
Heartbleed             11
Name: count, dtype: int64

In [9]:
print(
    df["label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

label
BENIGN              54.81
DoS Hulk             8.22
DDoS                 8.12
PortScan             8.01
DoS GoldenEye        5.48
FTP-Patator          4.46
SSH-Patator          3.30
DoS Slowhttptest     2.77
DoS slowloris        2.76
Bot                  2.03
Infiltration         0.04
Heartbleed           0.01
Name: proportion, dtype: float64

In [10]:
print("Number of attack classes:", df["label"].nunique())

Number of attack classes: 12

In [11]:
print("Protocols:")
print(df["protocol"].value_counts())

print("\nSource IPs:", df["src_ip"].nunique())
print("Destination IPs:", df["dst_ip"].nunique())

print("\nIncident IDs:", df["incident_id"].nunique())

Protocols:
Series([], Name: count, dtype: int64)

Source IPs: 0
Destination IPs: 0

Incident IDs: 95477

In [12]:
print("\nSample incident text:")
print(df["incident_text"].head(3).to_string(index=False))

Sample incident text:
Traffic label: BENIGN. Destination port: 80. Fl...
Attack: DDoS. Destination port: 80. Flow durati...
Traffic label: BENIGN. Destination port: 56026....

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
protocol,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
src_port,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dst_port,95477.0,7.106039e+03,1.709434e+04,0.0,53.000000,80.000000,4.430000e+02,6.553300e+04
flow_duration,95477.0,2.119650e+07,3.723002e+07,-12.0,2368.000000,325964.000000,1.209656e+07,1.199999e+08
total_fwd_packets,95477.0,1.420264e+01,1.144814e+03,1.0,2.000000,3.000000,8.000000e+00,2.186580e+05
total_bwd_packets,95477.0,1.663519e+01,1.533102e+03,0.0,1.000000,2.000000,6.000000e+00,2.912600e+05
total_len_fwd,95477.0,8.125965e+02,1.792775e+04,0.0,12.000000,68.000000,3.720000e+02,2.866110e+06
total_len_bwd,95477.0,2.660575e+04,3.361464e+06,0.0,6.000000,170.000000,3.525000e+03,6.410014e+08
flow_packets_s,95426.0,3.526591e+04,1.741008e+05,-2000000.0,0.782914,18.602857,1.451116e+03,4.000000e+06
fwd_packets_s,95477.0,2.886494e+04,1.616642e+05,0.0,0.530538,9.128106,1.036914e+03,3.000000e+06
bwd_packets_s,95477.0,6.446724e+03,3.862073e+04,0.0,0.083225,2.824325,6.532745e+01,2.000000e+06
fwd_packet_length_mean,95477.0,6.111526e+01,1.966934e+02,0.0,6.000000,33.000000,5.600000e+01,5.940857e+03
bwd_packet_length_mean,95477.0,4.446944e+02,7.697046e+02,0.0,6.000000,76.000000,3.617778e+02,4.370687e+03
min_packet_length,95477.0,1.091688e+01,2.613945e+01,0.0,0.000000,0.000000,6.000000e+00,1.306000e+03
max_packet_length,95477.0,1.452088e+03,2.573531e+03,0.0,6.000000,111.000000,1.460000e+03,2.336000e+04
packet_length_mean,95477.0,2.338327e+02,3.670973e+02,0.0,6.000000,63.600000,2.588462e+02,3.337143e+03
packet_length_std,95477.0,4.506748e+02,8.001661e+02,0.0,2.309401,35.054244,4.999613e+02,4.708990e+03
syn_flag_count,95477.0,4.603203e-02,2.095556e-01,0.0,0.000000,0.000000,0.000000e+00,1.000000e+00
ack_flag_count,95477.0,2.958304e-01,4.564175e-01,0.0,0.000000,0.000000,1.000000e+00,1.000000e+00
rst_flag_count,95477.0,1.780534e-04,1.334255e-02,0.0,0.000000,0.000000,0.000000e+00,1.000000e+00
psh_flag_count,95477.0,4.600584e-01,4.984047e-01,0.0,0.000000,0.000000,1.000000e+00,1.000000e+00
fin_flag_count,95477.0,3.308650e-02,1.788634e-01,0.0,0.000000,0.000000,0.000000e+00,1.000000e+00
fwd_syn_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bwd_syn_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fwd_ack_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bwd_ack_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fwd_rst_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bwd_rst_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fwd_psh_flags,95477.0,4.603203e-02,2.095556e-01,0.0,0.000000,0.000000,0.000000e+00,1.000000e+00
bwd_psh_flags,95477.0,0.000000e+00,0.000000e+00,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00
down_up_ratio,95477.0,6.567236e-01,6.501894e-01,0.0,0.000000,1.000000,1.000000e+00,8.000000e+00
init_win_bytes_forward,95477.0,1.080071e+04,1.510702e+04,-1.0,31.000000,946.000000,2.920000e+04,6.553500e+04
init_win_bytes_backward,95477.0,1.842340e+03,8.037815e+03,-1.0,-1.000000,62.000000,2.350000e+02,6.553500e+04
active_mean,95477.0,2.363442e+05,1.160453e+06,0.0,0.000000,0.000000,7.110000e+02,1.000000e+08
idle_mean,95477.0,1.265434e+07,2.871409e+07,0.0,0.000000,0.000000,6.810559e+06,1.200000e+08

In [14]:
print("Numeric columns:")
print(df.select_dtypes(include="number").columns.tolist())

print("\nCategorical columns:")
print(df.select_dtypes(include="object").columns.tolist())

Numeric columns:
['protocol', 'src_port', 'dst_port', 'flow_duration', 'total_fwd_packets', 'total_bwd_packets', 'total_len_fwd', 'total_len_bwd', 'flow_packets_s', 'fwd_packets_s', 'bwd_packets_s', 'fwd_packet_length_mean', 'bwd_packet_length_mean', 'min_packet_length', 'max_packet_length', 'packet_length_mean', 'packet_length_std', 'syn_flag_count', 'ack_flag_count', 'rst_flag_count', 'psh_flag_count', 'fin_flag_count', 'fwd_syn_flags', 'bwd_syn_flags', 'fwd_ack_flags', 'bwd_ack_flags', 'fwd_rst_flags', 'bwd_rst_flags', 'fwd_psh_flags', 'bwd_psh_flags', 'down_up_ratio', 'init_win_bytes_forward', 'init_win_bytes_backward', 'active_mean', 'idle_mean']

Categorical columns:
['label', 'src_ip', 'dst_ip', 'timestamp', 'incident_id', 'incident_text']

D:\NOPIS\tmp\ipykernel_5208\3898857952.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include="object").columns.tolist())

In [15]:
numeric_cols = df.select_dtypes(include="number").columns

negative_counts = (df[numeric_cols] < 0).sum()

print(
    negative_counts[negative_counts > 0]
)

flow_duration                  4
flow_packets_s                 4
init_win_bytes_forward     20353
init_win_bytes_backward    32709
dtype: int64

In [16]:
print(df.shape)
print(df.dtypes)
print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())
print(df["label"].value_counts())
print(df["label"].value_counts(normalize=True).mul(100).round(2))
print(df.describe().T)

(95477, 41)
label                          str
protocol                   float64
src_port                   float64
dst_port                   float64
flow_duration              float64
total_fwd_packets          float64
total_bwd_packets          float64
total_len_fwd              float64
total_len_bwd              float64
flow_packets_s             float64
fwd_packets_s              float64
bwd_packets_s              float64
fwd_packet_length_mean     float64
bwd_packet_length_mean     float64
min_packet_length          float64
max_packet_length          float64
packet_length_mean         float64
packet_length_std          float64
syn_flag_count             float64
ack_flag_count             float64
rst_flag_count             float64
psh_flag_count             float64
fin_flag_count             float64
fwd_syn_flags              float64
bwd_syn_flags              float64
fwd_ack_flags              float64
bwd_ack_flags              float64
fwd_rst_flags              float64
bwd_rst_flags              float64
fwd_psh_flags              float64
bwd_psh_flags              float64
down_up_ratio              float64
init_win_bytes_forward     float64
init_win_bytes_backward    float64
active_mean                float64
idle_mean                  float64
src_ip                         str
dst_ip                         str
timestamp                      str
incident_id                    str
incident_text                  str
dtype: object
label                          0
protocol                   95477
src_port                   95477
dst_port                       0
flow_duration                  0
total_fwd_packets              0
total_bwd_packets              0
total_len_fwd                  0
total_len_bwd                  0
flow_packets_s                51
fwd_packets_s                  0
bwd_packets_s                  0
fwd_packet_length_mean         0
bwd_packet_length_mean         0
min_packet_length              0
max_packet_length              0
packet_length_mean             0
packet_length_std              0
syn_flag_count                 0
ack_flag_count                 0
rst_flag_count                 0
psh_flag_count                 0
fin_flag_count                 0
fwd_syn_flags              95477
bwd_syn_flags              95477
fwd_ack_flags              95477
bwd_ack_flags              95477
fwd_rst_flags              95477
bwd_rst_flags              95477
fwd_psh_flags                  0
bwd_psh_flags                  0
down_up_ratio                  0
init_win_bytes_forward         0
init_win_bytes_backward        0
active_mean                    0
idle_mean                      0
src_ip                     95477
dst_ip                     95477
timestamp                  95477
incident_id                    0
incident_text                  0
dtype: int64
Duplicates: 0
label
BENIGN              52330
DoS Hulk             7847
DDoS                 7748
PortScan             7643
DoS GoldenEye        5236
FTP-Patator          4259
SSH-Patator          3149
DoS Slowhttptest     2645
DoS slowloris        2637
Bot                  1936
Infiltration           36
Heartbleed             11
Name: count, dtype: int64
label
BENIGN              54.81
DoS Hulk             8.22
DDoS                 8.12
PortScan             8.01
DoS GoldenEye        5.48
FTP-Patator          4.46
SSH-Patator          3.30
DoS Slowhttptest     2.77
DoS slowloris        2.76
Bot                  2.03
Infiltration         0.04
Heartbleed           0.01
Name: proportion, dtype: float64
                           count          mean           std        min  \
protocol                     0.0           NaN           NaN        NaN
src_port                     0.0           NaN           NaN        NaN
dst_port                 95477.0  7.106039e+03  1.709434e+04        0.0
flow_duration            95477.0  2.119650e+07  3.723002e+07      -12.0
total_fwd_packets        95477.0  1.420264e+01  1.144814e+03        1.0
total_bwd_packets        95477.0  1.663519e+01  1.533102e+03        0.0
total_len_fwd            95477.0  8.125965e+02  1.792775e+04        0.0
total_len_bwd            95477.0  2.660575e+04  3.361464e+06        0.0
flow_packets_s           95426.0  3.526591e+04  1.741008e+05 -2000000.0
fwd_packets_s            95477.0  2.886494e+04  1.616642e+05        0.0
bwd_packets_s            95477.0  6.446724e+03  3.862073e+04        0.0
fwd_packet_length_mean   95477.0  6.111526e+01  1.966934e+02        0.0
bwd_packet_length_mean   95477.0  4.446944e+02  7.697046e+02        0.0
min_packet_length        95477.0  1.091688e+01  2.613945e+01        0.0
max_packet_length        95477.0  1.452088e+03  2.573531e+03        0.0
packet_length_mean       95477.0  2.338327e+02  3.670973e+02        0.0
packet_length_std        95477.0  4.506748e+02  8.001661e+02        0.0
syn_flag_count           95477.0  4.603203e-02  2.095556e-01        0.0
ack_flag_count           95477.0  2.958304e-01  4.564175e-01        0.0
rst_flag_count           95477.0  1.780534e-04  1.334255e-02        0.0
psh_flag_count           95477.0  4.600584e-01  4.984047e-01        0.0
fin_flag_count           95477.0  3.308650e-02  1.788634e-01        0.0
fwd_syn_flags                0.0           NaN           NaN        NaN
bwd_syn_flags                0.0           NaN           NaN        NaN
fwd_ack_flags                0.0           NaN           NaN        NaN
bwd_ack_flags                0.0           NaN           NaN        NaN
fwd_rst_flags                0.0           NaN           NaN        NaN
bwd_rst_flags                0.0           NaN           NaN        NaN
fwd_psh_flags            95477.0  4.603203e-02  2.095556e-01        0.0
bwd_psh_flags            95477.0  0.000000e+00  0.000000e+00        0.0
down_up_ratio            95477.0  6.567236e-01  6.501894e-01        0.0
init_win_bytes_forward   95477.0  1.080071e+04  1.510702e+04       -1.0
init_win_bytes_backward  95477.0  1.842340e+03  8.037815e+03       -1.0
active_mean              95477.0  2.363442e+05  1.160453e+06        0.0
idle_mean                95477.0  1.265434e+07  2.871409e+07        0.0

                                 25%            50%           75%  \
protocol                         NaN            NaN           NaN
src_port                         NaN            NaN           NaN
dst_port                   53.000000      80.000000  4.430000e+02
flow_duration            2368.000000  325964.000000  1.209656e+07
total_fwd_packets           2.000000       3.000000  8.000000e+00
total_bwd_packets           1.000000       2.000000  6.000000e+00
total_len_fwd              12.000000      68.000000  3.720000e+02
total_len_bwd               6.000000     170.000000  3.525000e+03
flow_packets_s              0.782914      18.602857  1.451116e+03
fwd_packets_s               0.530538       9.128106  1.036914e+03
bwd_packets_s               0.083225       2.824325  6.532745e+01
fwd_packet_length_mean      6.000000      33.000000  5.600000e+01
bwd_packet_length_mean      6.000000      76.000000  3.617778e+02
min_packet_length           0.000000       0.000000  6.000000e+00
max_packet_length           6.000000     111.000000  1.460000e+03
packet_length_mean          6.000000      63.600000  2.588462e+02
packet_length_std           2.309401      35.054244  4.999613e+02
syn_flag_count              0.000000       0.000000  0.000000e+00
ack_flag_count              0.000000       0.000000  1.000000e+00
rst_flag_count              0.000000       0.000000  0.000000e+00
psh_flag_count              0.000000       0.000000  1.000000e+00
fin_flag_count              0.000000       0.000000  0.000000e+00
fwd_syn_flags                    NaN            NaN           NaN
bwd_syn_flags                    NaN            NaN           NaN
fwd_ack_flags                    NaN            NaN           NaN
bwd_ack_flags                    NaN            NaN           NaN
fwd_rst_flags                    NaN            NaN           NaN
bwd_rst_flags                    NaN            NaN           NaN
fwd_psh_flags               0.000000       0.000000  0.000000e+00
bwd_psh_flags               0.000000       0.000000  0.000000e+00
down_up_ratio               0.000000       1.000000  1.000000e+00
init_win_bytes_forward     31.000000     946.000000  2.920000e+04
init_win_bytes_backward    -1.000000      62.000000  2.350000e+02
active_mean                 0.000000       0.000000  7.110000e+02
idle_mean                   0.000000       0.000000  6.810559e+06

                                  max
protocol                          NaN
src_port                          NaN
dst_port                 6.553300e+04
flow_duration            1.199999e+08
total_fwd_packets        2.186580e+05
total_bwd_packets        2.912600e+05
total_len_fwd            2.866110e+06
total_len_bwd            6.410014e+08
flow_packets_s           4.000000e+06
fwd_packets_s            3.000000e+06
bwd_packets_s            2.000000e+06
fwd_packet_length_mean   5.940857e+03
bwd_packet_length_mean   4.370687e+03
min_packet_length        1.306000e+03
max_packet_length        2.336000e+04
packet_length_mean       3.337143e+03
packet_length_std        4.708990e+03
syn_flag_count           1.000000e+00
ack_flag_count           1.000000e+00
rst_flag_count           1.000000e+00
psh_flag_count           1.000000e+00
fin_flag_count           1.000000e+00
fwd_syn_flags                     NaN
bwd_syn_flags                     NaN
fwd_ack_flags                     NaN
bwd_ack_flags                     NaN
fwd_rst_flags                     NaN
bwd_rst_flags                     NaN
fwd_psh_flags            1.000000e+00
bwd_psh_flags            0.000000e+00
down_up_ratio            8.000000e+00
init_win_bytes_forward   6.553500e+04
init_win_bytes_backward  6.553500e+04
active_mean              1.000000e+08
idle_mean                1.200000e+08

In [17]:
print(df.isna().all()[df.isna().all()])

protocol         True
src_port         True
fwd_syn_flags    True
bwd_syn_flags    True
fwd_ack_flags    True
bwd_ack_flags    True
fwd_rst_flags    True
bwd_rst_flags    True
src_ip           True
dst_ip           True
timestamp        True
dtype: bool

In [18]:
empty_cols = df.columns[df.isna().all()]

df = df.drop(columns=empty_cols)

print(df.shape)

(95477, 30)

In [19]:
missing = df.isna().sum()

print(missing[missing > 0])

flow_packets_s    51
dtype: int64

In [20]:
missing_rows = df[df["flow_packets_s"].isna()]

print(missing_rows[["label", "flow_packets_s"]].to_string(index=False))

      label  flow_packets_s
   PortScan             NaN
   PortScan             NaN
FTP-Patator             NaN
   PortScan             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
FTP-Patator             NaN
   PortScan             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
   PortScan             NaN
     BENIGN             NaN
     BENIGN             NaN
   PortScan             NaN
        Bot             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
        Bot             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
        Bot             NaN
     BENIGN             NaN
   PortScan             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
        Bot             NaN
        Bot             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN

In [21]:
median_flow_packets = df["flow_packets_s"].median()

df["flow_packets_s"] = df["flow_packets_s"].fillna(median_flow_packets)

print("Median:", median_flow_packets)
print("Missing values:", df["flow_packets_s"].isna().sum())

Median: 18.60285691115
Missing values: 0

In [22]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [23]:
print(df["label"].value_counts())

label
BENIGN              52330
DoS Hulk             7847
DDoS                 7748
PortScan             7643
DoS GoldenEye        5236
FTP-Patator          4259
SSH-Patator          3149
DoS Slowhttptest     2645
DoS slowloris        2637
Bot                  1936
Infiltration           36
Heartbleed             11
Name: count, dtype: int64

In [24]:
print(
    df["label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

label
BENIGN              54.81
DoS Hulk             8.22
DDoS                 8.12
PortScan             8.01
DoS GoldenEye        5.48
FTP-Patator          4.46
SSH-Patator          3.30
DoS Slowhttptest     2.77
DoS slowloris        2.76
Bot                  2.03
Infiltration         0.04
Heartbleed           0.01
Name: proportion, dtype: float64

In [25]:
constant_cols = df.columns[df.nunique(dropna=False) <= 1]

print(constant_cols.tolist())

['bwd_psh_flags']

In [26]:
df = df.drop(columns=["bwd_psh_flags"])

In [27]:
print(df.shape)

(95477, 29)

In [28]:
numeric_cols = df.select_dtypes(include="number").columns

negative_counts = (df[numeric_cols] < 0).sum()

print(negative_counts[negative_counts > 0])

flow_duration                  4
flow_packets_s                 4
init_win_bytes_forward     20353
init_win_bytes_backward    32709
dtype: int64

In [29]:
for col in [
    "flow_duration",
    "flow_packets_s",
    "init_win_bytes_forward",
    "init_win_bytes_backward"
]:
    print(f"\n--- {col} ---")
    print(df.loc[df[col] < 0, col].value_counts().sort_index())

--- flow_duration ---
flow_duration
-12.0    1
-1.0     3
Name: count, dtype: int64

--- flow_packets_s ---
flow_packets_s
-2.000000e+06    3
-1.666667e+05    1
Name: count, dtype: int64

--- init_win_bytes_forward ---
init_win_bytes_forward
-1.0    20353
Name: count, dtype: int64

--- init_win_bytes_backward ---
init_win_bytes_backward
-1.0    32709
Name: count, dtype: int64

In [30]:
print(
    df.groupby("label")[
        ["init_win_bytes_forward", "init_win_bytes_backward"]
    ].apply(lambda x: (x == -1).sum())
)

                  init_win_bytes_forward  init_win_bytes_backward
label
BENIGN                             20352                    25962
Bot                                    0                        0
DDoS                                   0                     2821
DoS GoldenEye                          0                     1306
DoS Hulk                               0                      270
DoS Slowhttptest                       0                     1594
DoS slowloris                          0                      672
FTP-Patator                            0                       64
Heartbleed                             0                        0
Infiltration                           0                        3
PortScan                               1                        6
SSH-Patator                            0                       11

In [31]:
print("Forward window values:")
print(df["init_win_bytes_forward"].value_counts().head(10))

print("\nBackward window values:")
print(df["init_win_bytes_backward"].value_counts().head(10))

Forward window values:
init_win_bytes_forward
 29200.0    25044
-1.0        20353
 8192.0     12383
 1024.0      4741
 256.0       4716
 0.0         3148
 251.0       2595
 229.0       2401
 65535.0     1992
 274.0       1965
Name: count, dtype: int64

Backward window values:
init_win_bytes_backward
-1.0        32709
 235.0      12855
 0.0        12295
 229.0       5537
 227.0       4075
 247.0       2948
 256.0       1849
 237.0       1008
 33304.0      527
 29200.0      527
Name: count, dtype: int64

In [32]:
print(
    df[df["flow_duration"] < 0][
        ["label", "flow_duration", "total_fwd_packets",
         "total_bwd_packets", "flow_packets_s"]
    ].to_string(index=False)
)

 label  flow_duration  total_fwd_packets  total_bwd_packets  flow_packets_s
BENIGN           -1.0                1.0                1.0   -2.000000e+06
BENIGN           -1.0                1.0                1.0   -2.000000e+06
BENIGN          -12.0                1.0                1.0   -1.666667e+05
BENIGN           -1.0                1.0                1.0   -2.000000e+06

In [33]:
df = df[df["flow_duration"] >= 0].copy()

print(df.shape)

(95473, 29)

In [34]:
print(df[df["flow_packets_s"] < 0]["flow_packets_s"])

Series([], Name: flow_packets_s, dtype: float64)

In [35]:
numeric_cols = df.select_dtypes(include="number").columns

negative_counts = (df[numeric_cols] < 0).sum()

print(negative_counts[negative_counts > 0])

init_win_bytes_forward     20353
init_win_bytes_backward    32709
dtype: int64

In [36]:
print(df.columns.tolist())

['label', 'dst_port', 'flow_duration', 'total_fwd_packets', 'total_bwd_packets', 'total_len_fwd', 'total_len_bwd', 'flow_packets_s', 'fwd_packets_s', 'bwd_packets_s', 'fwd_packet_length_mean', 'bwd_packet_length_mean', 'min_packet_length', 'max_packet_length', 'packet_length_mean', 'packet_length_std', 'syn_flag_count', 'ack_flag_count', 'rst_flag_count', 'psh_flag_count', 'fin_flag_count', 'fwd_psh_flags', 'down_up_ratio', 'init_win_bytes_forward', 'init_win_bytes_backward', 'active_mean', 'idle_mean', 'incident_id', 'incident_text']

In [37]:
print("Total rows:", len(df))
print("Unique incidents:", df["incident_id"].nunique())

Total rows: 95473
Unique incidents: 95473

In [38]:
print(df["incident_text"].head(10).to_string(index=False))

Traffic label: BENIGN. Destination port: 80. Fl...
Attack: DDoS. Destination port: 80. Flow durati...
Traffic label: BENIGN. Destination port: 56026....
Attack: DoS Hulk. Destination port: 80. Flow du...
Traffic label: BENIGN. Destination port: 443. F...
Traffic label: BENIGN. Destination port: 53. Fl...
Traffic label: BENIGN. Destination port: 3283. ...
Traffic label: BENIGN. Destination port: 39628....
Attack: DDoS. Destination port: 80. Flow durati...
Traffic label: BENIGN. Destination port: 34445....

In [39]:
print(df.isna().sum()[df.isna().sum() > 0])

Series([], dtype: int64)

In [40]:
print(df.describe().T)

                           count          mean           std       min  \
dst_port                 95473.0  7.105803e+03  1.709409e+04  0.000000
flow_duration            95473.0  2.119739e+07  3.723054e+07  0.000000
total_fwd_packets        95473.0  1.420319e+01  1.144838e+03  1.000000
total_bwd_packets        95473.0  1.663584e+01  1.533134e+03  0.000000
total_len_fwd            95473.0  8.126303e+02  1.792813e+04  0.000000
total_len_bwd            95473.0  2.660686e+04  3.361535e+06  0.000000
flow_packets_s           95473.0  3.531315e+04  1.736843e+05  0.016727
fwd_packets_s            95473.0  2.886614e+04  1.616674e+05  0.000000
bwd_packets_s            95473.0  6.446994e+03  3.862152e+04  0.000000
fwd_packet_length_mean   95473.0  6.111763e+01  1.966972e+02  0.000000
bwd_packet_length_mean   95473.0  4.447101e+02  7.697166e+02  0.000000
min_packet_length        95473.0  1.091721e+01  2.613994e+01  0.000000
max_packet_length        95473.0  1.452146e+03  2.573569e+03  0.000000
packet_length_mean       95473.0  2.338415e+02  3.671025e+02  0.000000
packet_length_std        95473.0  4.506921e+02  8.001783e+02  0.000000
syn_flag_count           95473.0  4.603396e-02  2.095598e-01  0.000000
ack_flag_count           95473.0  2.958009e-01  4.564043e-01  0.000000
rst_flag_count           95473.0  1.780608e-04  1.334282e-02  0.000000
psh_flag_count           95473.0  4.600777e-01  4.984063e-01  0.000000
fin_flag_count           95473.0  3.307741e-02  1.788397e-01  0.000000
fwd_psh_flags            95473.0  4.603396e-02  2.095598e-01  0.000000
down_up_ratio            95473.0  6.567092e-01  6.501992e-01  0.000000
init_win_bytes_forward   95473.0  1.080115e+04  1.510718e+04 -1.000000
init_win_bytes_backward  95473.0  1.842018e+03  8.037469e+03 -1.000000
active_mean              95473.0  2.363541e+05  1.160476e+06  0.000000
idle_mean                95473.0  1.265487e+07  2.871457e+07  0.000000

                                 25%            50%           75%  \
dst_port                   53.000000      80.000000  4.430000e+02
flow_duration            2421.000000  326123.000000  1.209726e+07
total_fwd_packets           2.000000       3.000000  8.000000e+00
total_bwd_packets           1.000000       2.000000  6.000000e+00
total_len_fwd              12.000000      68.000000  3.720000e+02
total_len_bwd               6.000000     170.000000  3.525000e+03
flow_packets_s              0.783968      18.602857  1.418440e+03
fwd_packets_s               0.530723       9.133504  1.038422e+03
bwd_packets_s               0.083234       2.824838  6.532959e+01
fwd_packet_length_mean      6.000000      33.000000  5.600000e+01
bwd_packet_length_mean      6.000000      76.000000  3.618333e+02
min_packet_length           0.000000       0.000000  6.000000e+00
max_packet_length           6.000000     111.000000  1.460000e+03
packet_length_mean          6.000000      63.600000  2.588636e+02
packet_length_std           2.309401      35.054244  4.999882e+02
syn_flag_count              0.000000       0.000000  0.000000e+00
ack_flag_count              0.000000       0.000000  1.000000e+00
rst_flag_count              0.000000       0.000000  0.000000e+00
psh_flag_count              0.000000       0.000000  1.000000e+00
fin_flag_count              0.000000       0.000000  0.000000e+00
fwd_psh_flags               0.000000       0.000000  0.000000e+00
down_up_ratio               0.000000       1.000000  1.000000e+00
init_win_bytes_forward     31.000000     946.000000  2.920000e+04
init_win_bytes_backward    -1.000000      62.000000  2.350000e+02
active_mean                 0.000000       0.000000  7.110000e+02
idle_mean                   0.000000       0.000000  6.810749e+06

                                  max
dst_port                 6.553300e+04
flow_duration            1.199999e+08
total_fwd_packets        2.186580e+05
total_bwd_packets        2.912600e+05
total_len_fwd            2.866110e+06
total_len_bwd            6.410014e+08
flow_packets_s           4.000000e+06
fwd_packets_s            3.000000e+06
bwd_packets_s            2.000000e+06
fwd_packet_length_mean   5.940857e+03
bwd_packet_length_mean   4.370687e+03
min_packet_length        1.306000e+03
max_packet_length        2.336000e+04
packet_length_mean       3.337143e+03
packet_length_std        4.708990e+03
syn_flag_count           1.000000e+00
ack_flag_count           1.000000e+00
rst_flag_count           1.000000e+00
psh_flag_count           1.000000e+00
fin_flag_count           1.000000e+00
fwd_psh_flags            1.000000e+00
down_up_ratio            8.000000e+00
init_win_bytes_forward   6.553500e+04
init_win_bytes_backward  6.553500e+04
active_mean              1.000000e+08
idle_mean                1.200000e+08

In [41]:
for col in df.select_dtypes(include="number").columns:
    print(f"{col}: {df[col].nunique()} unique values")

dst_port: 11081 unique values
flow_duration: 68570 unique values
total_fwd_packets: 303 unique values
total_bwd_packets: 374 unique values
total_len_fwd: 4093 unique values
total_len_bwd: 7349 unique values
flow_packets_s: 72102 unique values
fwd_packets_s: 71631 unique values
bwd_packets_s: 62738 unique values
fwd_packet_length_mean: 9727 unique values
bwd_packet_length_mean: 10051 unique values
min_packet_length: 129 unique values
max_packet_length: 2676 unique values
packet_length_mean: 16805 unique values
packet_length_std: 25410 unique values
syn_flag_count: 2 unique values
ack_flag_count: 2 unique values
rst_flag_count: 2 unique values
psh_flag_count: 2 unique values
fin_flag_count: 2 unique values
fwd_psh_flags: 2 unique values
down_up_ratio: 9 unique values
init_win_bytes_forward: 1904 unique values
init_win_bytes_backward: 2187 unique values
active_mean: 16596 unique values
idle_mean: 10658 unique values

In [42]:
flag_cols = [
    "syn_flag_count",
    "ack_flag_count",
    "rst_flag_count",
    "psh_flag_count",
    "fin_flag_count",
    "fwd_psh_flags"
]

for col in flag_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

syn_flag_count
syn_flag_count
0.0    91078
1.0     4395
Name: count, dtype: int64

ack_flag_count
ack_flag_count
0.0    67232
1.0    28241
Name: count, dtype: int64

rst_flag_count
rst_flag_count
0.0    95456
1.0       17
Name: count, dtype: int64

psh_flag_count
psh_flag_count
0.0    51548
1.0    43925
Name: count, dtype: int64

fin_flag_count
fin_flag_count
0.0    92315
1.0     3158
Name: count, dtype: int64

fwd_psh_flags
fwd_psh_flags
0.0    91078
1.0     4395
Name: count, dtype: int64

In [43]:
corr = df.select_dtypes(include="number").corr()

print(corr.abs().unstack().sort_values(ascending=False).head(20))

idle_mean                idle_mean                  1.0
dst_port                 dst_port                   1.0
active_mean              active_mean                1.0
flow_duration            flow_duration              1.0
init_win_bytes_backward  init_win_bytes_backward    1.0
fwd_psh_flags            fwd_psh_flags              1.0
down_up_ratio            down_up_ratio              1.0
init_win_bytes_forward   init_win_bytes_forward     1.0
fwd_psh_flags            syn_flag_count             1.0
ack_flag_count           ack_flag_count             1.0
syn_flag_count           fwd_psh_flags              1.0
                         syn_flag_count             1.0
total_bwd_packets        total_bwd_packets          1.0
rst_flag_count           rst_flag_count             1.0
psh_flag_count           psh_flag_count             1.0
packet_length_std        packet_length_std          1.0
total_fwd_packets        total_fwd_packets          1.0
fin_flag_count           fin_flag_count             1.0
fwd_packets_s            fwd_packets_s              1.0
bwd_packet_length_mean   bwd_packet_length_mean     1.0
dtype: float64

In [44]:
df = df.drop(columns=["fwd_psh_flags"])

In [45]:
print(df.shape)

(95473, 28)

In [46]:
print(df.columns.tolist())

['label', 'dst_port', 'flow_duration', 'total_fwd_packets', 'total_bwd_packets', 'total_len_fwd', 'total_len_bwd', 'flow_packets_s', 'fwd_packets_s', 'bwd_packets_s', 'fwd_packet_length_mean', 'bwd_packet_length_mean', 'min_packet_length', 'max_packet_length', 'packet_length_mean', 'packet_length_std', 'syn_flag_count', 'ack_flag_count', 'rst_flag_count', 'psh_flag_count', 'fin_flag_count', 'down_up_ratio', 'init_win_bytes_forward', 'init_win_bytes_backward', 'active_mean', 'idle_mean', 'incident_id', 'incident_text']

In [47]:
df = df.drop(columns=["incident_id", "incident_text"])

print(df.columns.tolist())
print(df.shape)

['label', 'dst_port', 'flow_duration', 'total_fwd_packets', 'total_bwd_packets', 'total_len_fwd', 'total_len_bwd', 'flow_packets_s', 'fwd_packets_s', 'bwd_packets_s', 'fwd_packet_length_mean', 'bwd_packet_length_mean', 'min_packet_length', 'max_packet_length', 'packet_length_mean', 'packet_length_std', 'syn_flag_count', 'ack_flag_count', 'rst_flag_count', 'psh_flag_count', 'fin_flag_count', 'down_up_ratio', 'init_win_bytes_forward', 'init_win_bytes_backward', 'active_mean', 'idle_mean']
(95473, 26)

In [48]:
df.to_csv(
    r"D:\APCIRA\data\cleaned_network_data\cleaned_network_data.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!