In [1]:
import pandas as pd
from pathlib import Path

# Locate the repository root so the notebook runs from any checkout location.
PROJECT_ROOT = next(
    p for p in [Path.cwd(), *Path.cwd().parents]
    if (p / "requirements.txt").exists() and (p / "src").is_dir()
)

df = pd.read_parquet(PROJECT_ROOT / "data" / "processed" / "incidents_100k.parquet")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (97549, 41)

Columns:
['label', 'protocol', 'src_port', 'dst_port', 'flow_duration', 'total_fwd_packets', 'total_bwd_packets', 'total_len_fwd', 'total_len_bwd', 'flow_packets_s', 'fwd_packets_s', 'bwd_packets_s', 'fwd_packet_length_mean', 'bwd_packet_length_mean', 'min_packet_length', 'max_packet_length', 'packet_length_mean', 'packet_length_std', 'syn_flag_count', 'ack_flag_count', 'rst_flag_count', 'psh_flag_count', 'fin_flag_count', 'fwd_syn_flags', 'bwd_syn_flags', 'fwd_ack_flags', 'bwd_ack_flags', 'fwd_rst_flags', 'bwd_rst_flags', 'fwd_psh_flags', 'bwd_psh_flags', 'down_up_ratio', 'init_win_bytes_forward', 'init_win_bytes_backward', 'active_mean', 'idle_mean', 'src_ip', 'dst_ip', 'timestamp', 'incident_id', 'incident_text']

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97549 entries, 0 to 97548
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   label                    97549 non-null  object
 1   protocol                 0 non-null      float64
 2   src_port                 0 non-null      float64
 3   dst_port                 97549 non-null  float64
 4   flow_duration            97549 non-null  float64
 5   total_fwd_packets        97549 non-null  float64
 6   total_bwd_packets        97549 non-null  float64
 7   total_len_fwd            97549 non-null  float64
 8   total_len_bwd            97549 non-null  float64
 9   flow_packets_s           97491 non-null  float64
 10  fwd_packets_s            97549 non-null  float64
 11  bwd_packets_s            97549 non-null  float64
 12  fwd_packet_length_mean   97549 non-null  float64
 13  bwd_packet_length_mean   97549 non-null  float64
 14  min_packet_length        97549 non-null  float64
 15  max_packet_length        97549 non-null  float64
 16  packet_length_mean       97549 non-null  float64
 17  packet_length_std        97549 non-null  float64
 18  syn_flag_count           97549 non-null  float64
 19  ack_flag_count           97549 non-null  float64
 20  rst_flag_count           97549 non-null  float64
 21  psh_flag_count           97549 non-null  float64
 22  fin_flag_count           97549 non-null  float64
 23  fwd_syn_flags            0 non-null      float64
 24  bwd_syn_flags            0 non-null      float64
 25  fwd_ack_flags            0 non-null      float64
 26  bwd_ack_flags            0 non-null      float64
 27  fwd_rst_flags            0 non-null      float64
 28  bwd_rst_flags            0 non-null      float64
 29  fwd_psh_flags            97549 non-null  float64
 30  bwd_psh_flags            97549 non-null  float64
 31  down_up_ratio            97549 non-null  float64
 32  init_win_bytes_forward   97549 non-null  float64
 33  init_win_bytes_backward  97549 non-null  float64
 34  active_mean              97549 non-null  float64
 35  idle_mean                97549 non-null  float64
 36  src_ip                   0 non-null      object
 37  dst_ip                   0 non-null      object
 38  timestamp                0 non-null      object
 39  incident_id              97549 non-null  object
 40  incident_text            97549 non-null  object
dtypes: float64(35), object(6)
memory usage: 30.5+ MB

In [3]:
df.head()

,label,protocol,src_port,dst_port,flow_duration,total_fwd_packets,total_bwd_packets,total_len_fwd,total_len_bwd,flow_packets_s,...,down_up_ratio,init_win_bytes_forward,init_win_bytes_backward,active_mean,idle_mean,src_ip,dst_ip,timestamp,incident_id,incident_text
0,DoS Hulk,NaN,NaN,80.0,101175690.0,5.0,7.0,379.0,11595.0,0.118606,...,1.0,0.0,235.0,11043.00000,101000000.0,None,None,None,INC-000001,Attack: DoS Hulk. Destination port: 80. Flow d...
1,BENIGN,NaN,NaN,80.0,114.0,1.0,2.0,6.0,12.0,26315.789470,...,2.0,255.0,237.0,0.00000,0.0,None,None,None,INC-000002,Traffic label: BENIGN. Destination port: 80. F...
2,BENIGN,NaN,NaN,53.0,258.0,2.0,2.0,84.0,204.0,15503.875970,...,1.0,-1.0,-1.0,0.00000,0.0,None,None,None,INC-000003,Traffic label: BENIGN. Destination port: 53. F...
3,BENIGN,NaN,NaN,80.0,29126974.0,8.0,7.0,892.0,3938.0,0.514987,...,0.0,8192.0,980.0,35854.66667,8945248.0,None,None,None,INC-000004,Traffic label: BENIGN. Destination port: 80. F...
4,PortScan,NaN,NaN,1600.0,70.0,1.0,1.0,2.0,6.0,28571.428570,...,1.0,1024.0,0.0,0.00000,0.0,None,None,None,INC-000005,Attack: PortScan. Destination port: 1600. Flow...

In [4]:
df.sample(5)

,label,protocol,src_port,dst_port,flow_duration,total_fwd_packets,total_bwd_packets,total_len_fwd,total_len_bwd,flow_packets_s,...,down_up_ratio,init_win_bytes_forward,init_win_bytes_backward,active_mean,idle_mean,src_ip,dst_ip,timestamp,incident_id,incident_text
29317,BENIGN,NaN,NaN,443.0,260418.0,6.0,6.0,356.0,3782.0,46.079764,...,1.0,8192.0,60.0,0.0,0.0,None,None,None,INC-029318,Traffic label: BENIGN. Destination port: 443. ...
43926,BENIGN,NaN,NaN,443.0,3479328.0,5.0,1.0,117.0,41.0,1.724471,...,0.0,338.0,123.0,0.0,0.0,None,None,None,INC-043927,Traffic label: BENIGN. Destination port: 443. ...
78661,DDoS,NaN,NaN,80.0,1083119.0,3.0,5.0,26.0,11601.0,7.386077,...,1.0,8192.0,229.0,0.0,0.0,None,None,None,INC-078662,Attack: DDoS. Destination port: 80. Flow durat...
23358,BENIGN,NaN,NaN,53.0,24017.0,2.0,2.0,72.0,242.0,166.548695,...,1.0,-1.0,-1.0,0.0,0.0,None,None,None,INC-023359,Traffic label: BENIGN. Destination port: 53. F...
62394,PortScan,NaN,NaN,5907.0,35.0,1.0,1.0,0.0,6.0,57142.857140,...,1.0,29200.0,0.0,0.0,0.0,None,None,None,INC-062395,Attack: PortScan. Destination port: 5907. Flow...

In [5]:
missing = df.isnull().sum()

print(missing[missing > 0])

protocol          97549
src_port          97549
flow_packets_s       58
fwd_syn_flags     97549
bwd_syn_flags     97549
fwd_ack_flags     97549
bwd_ack_flags     97549
fwd_rst_flags     97549
bwd_rst_flags     97549
src_ip            97549
dst_ip            97549
timestamp         97549
dtype: int64

In [6]:
missing_pct = (df.isnull().sum() / len(df)) * 100

print(
    missing_pct[missing_pct > 0]
    .sort_values(ascending=False)
)

protocol          100.000000
src_port          100.000000
fwd_syn_flags     100.000000
bwd_syn_flags     100.000000
bwd_rst_flags     100.000000
fwd_ack_flags     100.000000
bwd_ack_flags     100.000000
fwd_rst_flags     100.000000
dst_ip            100.000000
src_ip            100.000000
timestamp         100.000000
flow_packets_s      0.059457
dtype: float64

In [7]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [8]:
print(df["label"].value_counts())

label
BENIGN                        52210
DDoS                           7843
PortScan                       7828
DoS Hulk                       7819
DoS GoldenEye                  5246
FTP-Patator                    4259
SSH-Patator                    3149
DoS slowloris                  2634
DoS Slowhttptest               2584
Bot                            1936
Web Attack - Brute Force       1323
Web Attack - XSS                651
Infiltration                     36
Web Attack - Sql Injection       20
Heartbleed                       11
Name: count, dtype: int64

In [9]:
print(
    df["label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

label
BENIGN                        53.52
DDoS                           8.04
PortScan                       8.02
DoS Hulk                       8.02
DoS GoldenEye                  5.38
FTP-Patator                    4.37
SSH-Patator                    3.23
DoS slowloris                  2.70
DoS Slowhttptest               2.65
Bot                            1.98
Web Attack - Brute Force       1.36
Web Attack - XSS               0.67
Infiltration                   0.04
Web Attack - Sql Injection     0.02
Heartbleed                     0.01
Name: proportion, dtype: float64

In [10]:
print("Number of attack classes:", df["label"].nunique())

Number of attack classes: 15

In [11]:
print("Protocols:")
print(df["protocol"].value_counts())

print("\nSource IPs:", df["src_ip"].nunique())
print("Destination IPs:", df["dst_ip"].nunique())

print("\nIncident IDs:", df["incident_id"].nunique())

Protocols:
Series([], Name: count, dtype: int64)

Source IPs: 0
Destination IPs: 0

Incident IDs: 97549

In [12]:
print("\nSample incident text:")
print(df["incident_text"].head(3).to_string(index=False))

Sample incident text:
Attack: DoS Hulk. Destination port: 80. Flow du...
Traffic label: BENIGN. Destination port: 80. Fl...
Traffic label: BENIGN. Destination port: 53. Fl...

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
protocol,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
src_port,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dst_port,97549.0,7.043989e+03,1.703728e+04,0.0,53.000000,80.000000,4.430000e+02,6.553200e+04
flow_duration,97549.0,2.064984e+07,3.665503e+07,-1.0,3166.000000,416362.000000,1.188472e+07,1.200000e+08
total_fwd_packets,97549.0,1.374926e+01,1.059243e+03,1.0,2.000000,3.000000,8.000000e+00,2.007550e+05
total_bwd_packets,97549.0,1.546728e+01,1.349150e+03,0.0,1.000000,2.000000,6.000000e+00,2.706860e+05
total_len_fwd,97549.0,8.106972e+02,1.722486e+04,0.0,6.000000,64.000000,3.660000e+02,2.866110e+06
total_len_bwd,97549.0,2.675878e+04,3.420487e+06,0.0,6.000000,158.000000,3.508000e+03,6.270479e+08
flow_packets_s,97491.0,3.524008e+04,1.745733e+05,-2000000.0,0.756590,15.946529,1.031814e+03,3.000000e+06
fwd_packets_s,97549.0,2.888430e+04,1.631035e+05,0.0,0.531041,7.674303,7.497628e+02,3.000000e+06
bwd_packets_s,97549.0,6.355329e+03,3.725968e+04,0.0,0.091478,2.715962,6.482982e+01,2.000000e+06
fwd_packet_length_mean,97549.0,5.994077e+01,1.959672e+02,0.0,6.000000,32.000000,5.500000e+01,5.940857e+03
bwd_packet_length_mean,97549.0,4.345093e+02,7.641630e+02,0.0,6.000000,69.000000,3.320000e+02,4.370687e+03
min_packet_length,97549.0,1.069186e+01,2.440015e+01,0.0,0.000000,0.000000,6.000000e+00,1.306000e+03
max_packet_length,97549.0,1.418736e+03,2.560535e+03,0.0,6.000000,104.000000,1.460000e+03,2.336000e+04
packet_length_mean,97549.0,2.283372e+02,3.644982e+02,0.0,6.000000,61.000000,2.412381e+02,3.337143e+03
packet_length_std,97549.0,4.405940e+02,7.960772e+02,0.0,2.309401,32.331615,4.682572e+02,4.708990e+03
syn_flag_count,97549.0,4.687900e-02,2.113807e-01,0.0,0.000000,0.000000,0.000000e+00,1.000000e+00
ack_flag_count,97549.0,2.915048e-01,4.544578e-01,0.0,0.000000,0.000000,1.000000e+00,1.000000e+00
rst_flag_count,97549.0,2.050252e-04,1.431731e-02,0.0,0.000000,0.000000,0.000000e+00,1.000000e+00
psh_flag_count,97549.0,4.670576e-01,4.989162e-01,0.0,0.000000,0.000000,1.000000e+00,1.000000e+00
fin_flag_count,97549.0,3.332684e-02,1.794895e-01,0.0,0.000000,0.000000,0.000000e+00,1.000000e+00
fwd_syn_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bwd_syn_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fwd_ack_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bwd_ack_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fwd_rst_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bwd_rst_flags,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fwd_psh_flags,97549.0,4.687900e-02,2.113807e-01,0.0,0.000000,0.000000,0.000000e+00,1.000000e+00
bwd_psh_flags,97549.0,0.000000e+00,0.000000e+00,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00
down_up_ratio,97549.0,6.500118e-01,6.643359e-01,0.0,0.000000,1.000000,1.000000e+00,2.100000e+01
init_win_bytes_forward,97549.0,1.103349e+04,1.512534e+04,-1.0,36.000000,1013.000000,2.920000e+04,6.553500e+04
init_win_bytes_backward,97549.0,2.269282e+03,8.588127e+03,-1.0,-1.000000,68.000000,2.350000e+02,6.553500e+04
active_mean,97549.0,2.258415e+05,1.079720e+06,0.0,0.000000,0.000000,9.800000e+01,3.430000e+07
idle_mean,97549.0,1.239044e+07,2.847279e+07,0.0,0.000000,0.000000,6.488112e+06,1.200000e+08

In [14]:
print("Numeric columns:")
print(df.select_dtypes(include="number").columns.tolist())

print("\nCategorical columns:")
print(df.select_dtypes(include="object").columns.tolist())

Numeric columns:
['protocol', 'src_port', 'dst_port', 'flow_duration', 'total_fwd_packets', 'total_bwd_packets', 'total_len_fwd', 'total_len_bwd', 'flow_packets_s', 'fwd_packets_s', 'bwd_packets_s', 'fwd_packet_length_mean', 'bwd_packet_length_mean', 'min_packet_length', 'max_packet_length', 'packet_length_mean', 'packet_length_std', 'syn_flag_count', 'ack_flag_count', 'rst_flag_count', 'psh_flag_count', 'fin_flag_count', 'fwd_syn_flags', 'bwd_syn_flags', 'fwd_ack_flags', 'bwd_ack_flags', 'fwd_rst_flags', 'bwd_rst_flags', 'fwd_psh_flags', 'bwd_psh_flags', 'down_up_ratio', 'init_win_bytes_forward', 'init_win_bytes_backward', 'active_mean', 'idle_mean']

Categorical columns:
['label', 'src_ip', 'dst_ip', 'timestamp', 'incident_id', 'incident_text']

In [15]:
numeric_cols = df.select_dtypes(include="number").columns

negative_counts = (df[numeric_cols] < 0).sum()

print(
    negative_counts[negative_counts > 0]
)

flow_duration                  1
flow_packets_s                 1
init_win_bytes_forward     20496
init_win_bytes_backward    32926
dtype: int64

In [16]:
print(df.shape)
print(df.dtypes)
print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())
print(df["label"].value_counts())
print(df["label"].value_counts(normalize=True).mul(100).round(2))
print(df.describe().T)

(97549, 41)
label                       object
protocol                   float64
src_port                   float64
dst_port                   float64
flow_duration              float64
total_fwd_packets          float64
total_bwd_packets          float64
total_len_fwd              float64
total_len_bwd              float64
flow_packets_s             float64
fwd_packets_s              float64
bwd_packets_s              float64
fwd_packet_length_mean     float64
bwd_packet_length_mean     float64
min_packet_length          float64
max_packet_length          float64
packet_length_mean         float64
packet_length_std          float64
syn_flag_count             float64
ack_flag_count             float64
rst_flag_count             float64
psh_flag_count             float64
fin_flag_count             float64
fwd_syn_flags              float64
bwd_syn_flags              float64
fwd_ack_flags              float64
bwd_ack_flags              float64
fwd_rst_flags              float64
bwd_rst_flags              float64
fwd_psh_flags              float64
bwd_psh_flags              float64
down_up_ratio              float64
init_win_bytes_forward     float64
init_win_bytes_backward    float64
active_mean                float64
idle_mean                  float64
src_ip                      object
dst_ip                      object
timestamp                   object
incident_id                 object
incident_text               object
dtype: object
label                          0
protocol                   97549
src_port                   97549
dst_port                       0
flow_duration                  0
total_fwd_packets              0
total_bwd_packets              0
total_len_fwd                  0
total_len_bwd                  0
flow_packets_s                58
fwd_packets_s                  0
bwd_packets_s                  0
fwd_packet_length_mean         0
bwd_packet_length_mean         0
min_packet_length              0
max_packet_length              0
packet_length_mean             0
packet_length_std              0
syn_flag_count                 0
ack_flag_count                 0
rst_flag_count                 0
psh_flag_count                 0
fin_flag_count                 0
fwd_syn_flags              97549
bwd_syn_flags              97549
fwd_ack_flags              97549
bwd_ack_flags              97549
fwd_rst_flags              97549
bwd_rst_flags              97549
fwd_psh_flags                  0
bwd_psh_flags                  0
down_up_ratio                  0
init_win_bytes_forward         0
init_win_bytes_backward        0
active_mean                    0
idle_mean                      0
src_ip                     97549
dst_ip                     97549
timestamp                  97549
incident_id                    0
incident_text                  0
dtype: int64

Duplicates: 0
label
BENIGN                        52210
DDoS                           7843
PortScan                       7828
DoS Hulk                       7819
DoS GoldenEye                  5246
FTP-Patator                    4259
SSH-Patator                    3149
DoS slowloris                  2634
DoS Slowhttptest               2584
Bot                            1936
Web Attack - Brute Force       1323
Web Attack - XSS                651
Infiltration                     36
Web Attack - Sql Injection       20
Heartbleed                       11
Name: count, dtype: int64
label
BENIGN                        53.52
DDoS                           8.04
PortScan                       8.02
DoS Hulk                       8.02
DoS GoldenEye                  5.38
FTP-Patator                    4.37
SSH-Patator                    3.23
DoS slowloris                  2.70
DoS Slowhttptest               2.65
Bot                            1.98
Web Attack - Brute Force       1.36
Web Attack - XSS               0.67
Infiltration                   0.04
Web Attack - Sql Injection     0.02
Heartbleed                     0.01
Name: proportion, dtype: float64

                           count          mean           std        min  \
protocol                     0.0           NaN           NaN        NaN
src_port                     0.0           NaN           NaN        NaN
dst_port                 97549.0  7.043989e+03  1.703728e+04        0.0
flow_duration            97549.0  2.064984e+07  3.665503e+07       -1.0
total_fwd_packets        97549.0  1.374926e+01  1.059243e+03        1.0
total_bwd_packets        97549.0  1.546728e+01  1.349150e+03        0.0
total_len_fwd            97549.0  8.106972e+02  1.722486e+04        0.0
total_len_bwd            97549.0  2.675878e+04  3.420487e+06        0.0
flow_packets_s           97491.0  3.524008e+04  1.745733e+05 -2000000.0
fwd_packets_s            97549.0  2.888430e+04  1.631035e+05        0.0
bwd_packets_s            97549.0  6.355329e+03  3.725968e+04        0.0
fwd_packet_length_mean   97549.0  5.994077e+01  1.959672e+02        0.0
bwd_packet_length_mean   97549.0  4.345093e+02  7.641630e+02        0.0
min_packet_length        97549.0  1.069186e+01  2.440015e+01        0.0
max_packet_length        97549.0  1.418736e+03  2.560535e+03        0.0
packet_length_mean       97549.0  2.283372e+02  3.644982e+02        0.0
packet_length_std        97549.0  4.405940e+02  7.960772e+02        0.0
syn_flag_count           97549.0  4.687900e-02  2.113807e-01        0.0
ack_flag_count           97549.0  2.915048e-01  4.544578e-01        0.0
rst_flag_count           97549.0  2.050252e-04  1.431731e-02        0.0
psh_flag_count           97549.0  4.670576e-01  4.989162e-01        0.0
fin_flag_count           97549.0  3.332684e-02  1.794895e-01        0.0
fwd_syn_flags                0.0           NaN           NaN        NaN
bwd_syn_flags                0.0           NaN           NaN        NaN
fwd_ack_flags                0.0           NaN           NaN        NaN
bwd_ack_flags                0.0           NaN           NaN        NaN
fwd_rst_flags                0.0           NaN           NaN        NaN
bwd_rst_flags                0.0           NaN           NaN        NaN
fwd_psh_flags            97549.0  4.687900e-02  2.113807e-01        0.0
bwd_psh_flags            97549.0  0.000000e+00  0.000000e+00        0.0
down_up_ratio            97549.0  6.500118e-01  6.643359e-01        0.0
init_win_bytes_forward   97549.0  1.103349e+04  1.512534e+04       -1.0
init_win_bytes_backward  97549.0  2.269282e+03  8.588127e+03       -1.0
active_mean              97549.0  2.258415e+05  1.079720e+06        0.0
idle_mean                97549.0  1.239044e+07  2.847279e+07        0.0

                                 25%            50%           75%  \
protocol                         NaN            NaN           NaN
src_port                         NaN            NaN           NaN
dst_port                   53.000000      80.000000  4.430000e+02
flow_duration            3166.000000  416362.000000  1.188472e+07
total_fwd_packets           2.000000       3.000000  8.000000e+00
total_bwd_packets           1.000000       2.000000  6.000000e+00
total_len_fwd               6.000000      64.000000  3.660000e+02
total_len_bwd               6.000000     158.000000  3.508000e+03
flow_packets_s              0.756590      15.946529  1.031814e+03
fwd_packets_s               0.531041       7.674303  7.497628e+02
bwd_packets_s               0.091478       2.715962  6.482982e+01
fwd_packet_length_mean      6.000000      32.000000  5.500000e+01
bwd_packet_length_mean      6.000000      69.000000  3.320000e+02
min_packet_length           0.000000       0.000000  6.000000e+00
max_packet_length           6.000000     104.000000  1.460000e+03
packet_length_mean          6.000000      61.000000  2.412381e+02
packet_length_std           2.309401      32.331615  4.682572e+02
syn_flag_count              0.000000       0.000000  0.000000e+00
ack_flag_count              0.000000       0.000000  1.000000e+00
rst_flag_count              0.000000       0.000000  0.000000e+00
psh_flag_count              0.000000       0.000000  1.000000e+00
fin_flag_count              0.000000       0.000000  0.000000e+00
fwd_syn_flags                    NaN            NaN           NaN
bwd_syn_flags                    NaN            NaN           NaN
fwd_ack_flags                    NaN            NaN           NaN
bwd_ack_flags                    NaN            NaN           NaN
fwd_rst_flags                    NaN            NaN           NaN
bwd_rst_flags                    NaN            NaN           NaN
fwd_psh_flags               0.000000       0.000000  0.000000e+00
bwd_psh_flags               0.000000       0.000000  0.000000e+00
down_up_ratio               0.000000       1.000000  1.000000e+00
init_win_bytes_forward     36.000000    1013.000000  2.920000e+04
init_win_bytes_backward    -1.000000      68.000000  2.350000e+02
active_mean                 0.000000       0.000000  9.800000e+01
idle_mean                   0.000000       0.000000  6.488112e+06

                                  max
protocol                          NaN
src_port                          NaN
dst_port                 6.553200e+04
flow_duration            1.200000e+08
total_fwd_packets        2.007550e+05
total_bwd_packets        2.706860e+05
total_len_fwd            2.866110e+06
total_len_bwd            6.270479e+08
flow_packets_s           3.000000e+06
fwd_packets_s            3.000000e+06
bwd_packets_s            2.000000e+06
fwd_packet_length_mean   5.940857e+03
bwd_packet_length_mean   4.370687e+03
min_packet_length        1.306000e+03
max_packet_length        2.336000e+04
packet_length_mean       3.337143e+03
packet_length_std        4.708990e+03
syn_flag_count           1.000000e+00
ack_flag_count           1.000000e+00
rst_flag_count           1.000000e+00
psh_flag_count           1.000000e+00
fin_flag_count           1.000000e+00
fwd_syn_flags                     NaN
bwd_syn_flags                     NaN
fwd_ack_flags                     NaN
bwd_ack_flags                     NaN
fwd_rst_flags                     NaN
bwd_rst_flags                     NaN
fwd_psh_flags            1.000000e+00
bwd_psh_flags            0.000000e+00
down_up_ratio            2.100000e+01
init_win_bytes_forward   6.553500e+04
init_win_bytes_backward  6.553500e+04
active_mean              3.430000e+07
idle_mean                1.200000e+08

In [17]:
print(df.isna().all()[df.isna().all()])

protocol         True
src_port         True
fwd_syn_flags    True
bwd_syn_flags    True
fwd_ack_flags    True
bwd_ack_flags    True
fwd_rst_flags    True
bwd_rst_flags    True
src_ip           True
dst_ip           True
timestamp        True
dtype: bool

In [18]:
empty_cols = df.columns[df.isna().all()]

df = df.drop(columns=empty_cols)

print(df.shape)

(97549, 30)

In [19]:
missing = df.isna().sum()

print(missing[missing > 0])

flow_packets_s    58
dtype: int64

In [20]:
missing_rows = df[df["flow_packets_s"].isna()]

print(missing_rows[["label", "flow_packets_s"]].to_string(index=False))

      label  flow_packets_s
     BENIGN             NaN
     BENIGN             NaN
   PortScan             NaN
     BENIGN             NaN
   PortScan             NaN
     BENIGN             NaN
     BENIGN             NaN
FTP-Patator             NaN
        Bot             NaN
   PortScan             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
   PortScan             NaN
     BENIGN             NaN
        Bot             NaN
       DDoS             NaN
   PortScan             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
FTP-Patator             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
   PortScan             NaN
     BENIGN             NaN
     BENIGN             NaN
   PortScan             NaN
   PortScan             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
   PortScan             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
        Bot             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
   PortScan             NaN
   PortScan             NaN
   PortScan             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
     BENIGN             NaN
        Bot             NaN
        Bot             NaN

In [21]:
median_flow_packets = df["flow_packets_s"].median()

df["flow_packets_s"] = df["flow_packets_s"].fillna(median_flow_packets)

print("Median:", median_flow_packets)
print("Missing values:", df["flow_packets_s"].isna().sum())

Median: 15.94652901
Missing values: 0

In [22]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [23]:
print(df["label"].value_counts())

label
BENIGN                        52210
DDoS                           7843
PortScan                       7828
DoS Hulk                       7819
DoS GoldenEye                  5246
FTP-Patator                    4259
SSH-Patator                    3149
DoS slowloris                  2634
DoS Slowhttptest               2584
Bot                            1936
Web Attack - Brute Force       1323
Web Attack - XSS                651
Infiltration                     36
Web Attack - Sql Injection       20
Heartbleed                       11
Name: count, dtype: int64

In [24]:
print(
    df["label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

label
BENIGN                        53.52
DDoS                           8.04
PortScan                       8.02
DoS Hulk                       8.02
DoS GoldenEye                  5.38
FTP-Patator                    4.37
SSH-Patator                    3.23
DoS slowloris                  2.70
DoS Slowhttptest               2.65
Bot                            1.98
Web Attack - Brute Force       1.36
Web Attack - XSS               0.67
Infiltration                   0.04
Web Attack - Sql Injection     0.02
Heartbleed                     0.01
Name: proportion, dtype: float64

In [25]:
constant_cols = df.columns[df.nunique(dropna=False) <= 1]

print(constant_cols.tolist())

['bwd_psh_flags']

In [26]:
df = df.drop(columns=["bwd_psh_flags"])

In [27]:
print(df.shape)

(97549, 29)

In [28]:
numeric_cols = df.select_dtypes(include="number").columns

negative_counts = (df[numeric_cols] < 0).sum()

print(negative_counts[negative_counts > 0])

flow_duration                  1
flow_packets_s                 1
init_win_bytes_forward     20496
init_win_bytes_backward    32926
dtype: int64

In [29]:
for col in [
    "flow_duration",
    "flow_packets_s",
    "init_win_bytes_forward",
    "init_win_bytes_backward"
]:
    print(f"\n--- {col} ---")
    print(df.loc[df[col] < 0, col].value_counts().sort_index())

--- flow_duration ---
flow_duration
-1.0    1
Name: count, dtype: int64

--- flow_packets_s ---
flow_packets_s
-2000000.0    1
Name: count, dtype: int64

--- init_win_bytes_forward ---
init_win_bytes_forward
-1.0    20496
Name: count, dtype: int64

--- init_win_bytes_backward ---
init_win_bytes_backward
-1.0    32926
Name: count, dtype: int64

In [30]:
print(
    df.groupby("label")[
        ["init_win_bytes_forward", "init_win_bytes_backward"]
    ].apply(lambda x: (x == -1).sum())
)

                            init_win_bytes_forward  init_win_bytes_backward
label
BENIGN                                       20496                    26133
Bot                                              0                        0
DDoS                                             0                     2839
DoS GoldenEye                                    0                     1309
DoS Hulk                                         0                      276
DoS Slowhttptest                                 0                     1579
DoS slowloris                                    0                      692
FTP-Patator                                      0                       64
Heartbleed                                       0                        0
Infiltration                                     0                        3
PortScan                                         0                        3
SSH-Patator                                      0                       11
Web Attack - Brute Force                         0                        0
Web Attack - Sql Injection                       0                        0
Web Attack - XSS                                 0                       17

In [31]:
print("Forward window values:")
print(df["init_win_bytes_forward"].value_counts().head(10))

print("\nBackward window values:")
print(df["init_win_bytes_backward"].value_counts().head(10))

Forward window values:
init_win_bytes_forward
 29200.0    26740
-1.0        20496
 8192.0     12205
 1024.0      4880
 256.0       4773
 0.0         3241
 251.0       2559
 229.0       2462
 65535.0     1983
 274.0       1921
Name: count, dtype: int64

Backward window values:
init_win_bytes_backward
-1.0        32926
 235.0      12890
 0.0        12531
 229.0       5644
 227.0       4076
 247.0       2964
 28960.0     2171
 256.0       1773
 237.0       1011
 33304.0      522
Name: count, dtype: int64

In [32]:
print(
    df[df["flow_duration"] < 0][
        ["label", "flow_duration", "total_fwd_packets",
         "total_bwd_packets", "flow_packets_s"]
    ].to_string(index=False)
)

 label  flow_duration  total_fwd_packets  total_bwd_packets  flow_packets_s
BENIGN           -1.0                1.0                1.0      -2000000.0

In [33]:
df = df[df["flow_duration"] >= 0].copy()

print(df.shape)

(97548, 29)

In [34]:
print(df[df["flow_packets_s"] < 0]["flow_packets_s"])

Series([], Name: flow_packets_s, dtype: float64)

In [35]:
numeric_cols = df.select_dtypes(include="number").columns

negative_counts = (df[numeric_cols] < 0).sum()

print(negative_counts[negative_counts > 0])

init_win_bytes_forward     20496
init_win_bytes_backward    32926
dtype: int64

In [36]:
print(df.columns.tolist())

['label', 'dst_port', 'flow_duration', 'total_fwd_packets', 'total_bwd_packets', 'total_len_fwd', 'total_len_bwd', 'flow_packets_s', 'fwd_packets_s', 'bwd_packets_s', 'fwd_packet_length_mean', 'bwd_packet_length_mean', 'min_packet_length', 'max_packet_length', 'packet_length_mean', 'packet_length_std', 'syn_flag_count', 'ack_flag_count', 'rst_flag_count', 'psh_flag_count', 'fin_flag_count', 'fwd_psh_flags', 'down_up_ratio', 'init_win_bytes_forward', 'init_win_bytes_backward', 'active_mean', 'idle_mean', 'incident_id', 'incident_text']

In [37]:
print("Total rows:", len(df))
print("Unique incidents:", df["incident_id"].nunique())

Total rows: 97548
Unique incidents: 97548

In [38]:
print(df["incident_text"].head(10).to_string(index=False))

Attack: DoS Hulk. Destination port: 80. Flow du...
Traffic label: BENIGN. Destination port: 80. Fl...
Traffic label: BENIGN. Destination port: 53. Fl...
Traffic label: BENIGN. Destination port: 80. Fl...
Attack: PortScan. Destination port: 1600. Flow ...
Attack: DDoS. Destination port: 80. Flow durati...
Traffic label: BENIGN. Destination port: 52683....
Traffic label: BENIGN. Destination port: 80. Fl...
Traffic label: BENIGN. Destination port: 53. Fl...
Attack: PortScan. Destination port: 3030. Flow ...

In [39]:
print(df.isna().sum()[df.isna().sum() > 0])

Series([], dtype: int64)

In [40]:
print(df.describe().T)

                           count          mean           std       min  \
dst_port                 97548.0  7.043537e+03  1.703679e+04  0.000000
flow_duration            97548.0  2.065006e+07  3.665516e+07  0.000000
total_fwd_packets        97548.0  1.374940e+01  1.059248e+03  1.000000
total_bwd_packets        97548.0  1.546743e+01  1.349157e+03  0.000000
total_len_fwd            97548.0  8.107055e+02  1.722495e+04  0.000000
total_len_bwd            97548.0  2.675905e+04  3.420505e+06  0.000000
flow_packets_s           97548.0  3.524000e+04  1.744027e+05  0.016718
fwd_packets_s            97548.0  2.888460e+04  1.631043e+05  0.000000
bwd_packets_s            97548.0  6.355394e+03  3.725986e+04  0.000000
fwd_packet_length_mean   97548.0  5.994133e+01  1.959681e+02  0.000000
bwd_packet_length_mean   97548.0  4.345137e+02  7.641657e+02  0.000000
min_packet_length        97548.0  1.069191e+01  2.440027e+01  0.000000
max_packet_length        97548.0  1.418751e+03  2.560544e+03  0.000000
packet_length_mean       97548.0  2.283394e+02  3.644994e+02  0.000000
packet_length_std        97548.0  4.405985e+02  7.960800e+02  0.000000
syn_flag_count           97548.0  4.687948e-02  2.113818e-01  0.000000
ack_flag_count           97548.0  2.914975e-01  4.544544e-01  0.000000
rst_flag_count           97548.0  2.050273e-04  1.431738e-02  0.000000
psh_flag_count           97548.0  4.670624e-01  4.989165e-01  0.000000
fin_flag_count           97548.0  3.332718e-02  1.794904e-01  0.000000
fwd_psh_flags            97548.0  4.687948e-02  2.113818e-01  0.000000
down_up_ratio            97548.0  6.500082e-01  6.643384e-01  0.000000
init_win_bytes_forward   97548.0  1.103356e+04  1.512541e+04 -1.000000
init_win_bytes_backward  97548.0  2.268648e+03  8.585882e+03 -1.000000
active_mean              97548.0  2.258438e+05  1.079725e+06  0.000000
idle_mean                97548.0  1.239057e+07  2.847291e+07  0.000000

                                 25%            50%           75%  \
dst_port                   53.000000      80.000000  4.430000e+02
flow_duration            3175.750000  416562.500000  1.188477e+07
total_fwd_packets           2.000000       3.000000  8.000000e+00
total_bwd_packets           1.000000       2.000000  6.000000e+00
total_len_fwd               6.000000      64.000000  3.660000e+02
total_len_bwd               6.000000     158.000000  3.508000e+03
flow_packets_s              0.756998      15.946529  1.007588e+03
fwd_packets_s               0.531046       7.674538  7.502214e+02
bwd_packets_s               0.091481       2.716230  6.482982e+01
fwd_packet_length_mean      6.000000      32.000000  5.500000e+01
bwd_packet_length_mean      6.000000      69.000000  3.320000e+02
min_packet_length           0.000000       0.000000  6.000000e+00
max_packet_length           6.000000     104.000000  1.460000e+03
packet_length_mean          6.000000      61.000000  2.412486e+02
packet_length_std           2.309401      32.331615  4.682854e+02
syn_flag_count              0.000000       0.000000  0.000000e+00
ack_flag_count              0.000000       0.000000  1.000000e+00
rst_flag_count              0.000000       0.000000  0.000000e+00
psh_flag_count              0.000000       0.000000  1.000000e+00
fin_flag_count              0.000000       0.000000  0.000000e+00
fwd_psh_flags               0.000000       0.000000  0.000000e+00
down_up_ratio               0.000000       1.000000  1.000000e+00
init_win_bytes_forward     36.000000    1013.000000  2.920000e+04
init_win_bytes_backward    -1.000000      68.000000  2.350000e+02
active_mean                 0.000000       0.000000  9.800000e+01
idle_mean                   0.000000       0.000000  6.488186e+06

                                  max
dst_port                 6.553200e+04
flow_duration            1.200000e+08
total_fwd_packets        2.007550e+05
total_bwd_packets        2.706860e+05
total_len_fwd            2.866110e+06
total_len_bwd            6.270479e+08
flow_packets_s           3.000000e+06
fwd_packets_s            3.000000e+06
bwd_packets_s            2.000000e+06
fwd_packet_length_mean   5.940857e+03
bwd_packet_length_mean   4.370687e+03
min_packet_length        1.306000e+03
max_packet_length        2.336000e+04
packet_length_mean       3.337143e+03
packet_length_std        4.708990e+03
syn_flag_count           1.000000e+00
ack_flag_count           1.000000e+00
rst_flag_count           1.000000e+00
psh_flag_count           1.000000e+00
fin_flag_count           1.000000e+00
fwd_psh_flags            1.000000e+00
down_up_ratio            2.100000e+01
init_win_bytes_forward   6.553500e+04
init_win_bytes_backward  6.553500e+04
active_mean              3.430000e+07
idle_mean                1.200000e+08

In [41]:
for col in df.select_dtypes(include="number").columns:
    print(f"{col}: {df[col].nunique()} unique values")

dst_port: 11050 unique values

flow_duration: 70197 unique values
total_fwd_packets: 302 unique values
total_bwd_packets: 353 unique values
total_len_fwd: 4007 unique values
total_len_bwd: 7208 unique values
flow_packets_s: 73752 unique values
fwd_packets_s: 73327 unique values
bwd_packets_s: 64358 unique values
fwd_packet_length_mean: 9574 unique values
bwd_packet_length_mean: 9784 unique values
min_packet_length: 122 unique values
max_packet_length: 2590 unique values
packet_length_mean: 16562 unique values
packet_length_std: 25245 unique values
syn_flag_count: 2 unique values
ack_flag_count: 2 unique values
rst_flag_count: 2 unique values
psh_flag_count: 2 unique values
fin_flag_count: 2 unique values
fwd_psh_flags: 2 unique values
down_up_ratio: 10 unique values
init_win_bytes_forward: 1904 unique values
init_win_bytes_backward: 2185 unique values
active_mean: 16471 unique values
idle_mean: 10635 unique values

In [42]:
flag_cols = [
    "syn_flag_count",
    "ack_flag_count",
    "rst_flag_count",
    "psh_flag_count",
    "fin_flag_count",
    "fwd_psh_flags"
]

for col in flag_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

syn_flag_count
syn_flag_count
0.0    92975
1.0     4573
Name: count, dtype: int64

ack_flag_count
ack_flag_count
0.0    69113
1.0    28435
Name: count, dtype: int64

rst_flag_count
rst_flag_count
0.0    97528
1.0       20
Name: count, dtype: int64

psh_flag_count
psh_flag_count
0.0    51987
1.0    45561
Name: count, dtype: int64

fin_flag_count
fin_flag_count
0.0    94297
1.0     3251
Name: count, dtype: int64

fwd_psh_flags
fwd_psh_flags
0.0    92975
1.0     4573
Name: count, dtype: int64

In [43]:
corr = df.select_dtypes(include="number").corr()

print(corr.abs().unstack().sort_values(ascending=False).head(20))

idle_mean                idle_mean                  1.0
dst_port                 dst_port                   1.0
active_mean              active_mean                1.0
flow_duration            flow_duration              1.0
fwd_psh_flags            fwd_psh_flags              1.0
init_win_bytes_backward  init_win_bytes_backward    1.0
init_win_bytes_forward   init_win_bytes_forward     1.0
down_up_ratio            down_up_ratio              1.0
fwd_psh_flags            syn_flag_count             1.0
rst_flag_count           rst_flag_count             1.0
fin_flag_count           fin_flag_count             1.0
psh_flag_count           psh_flag_count             1.0
total_fwd_packets        total_fwd_packets          1.0
ack_flag_count           ack_flag_count             1.0
syn_flag_count           syn_flag_count             1.0
                         fwd_psh_flags              1.0
total_bwd_packets        total_bwd_packets          1.0
min_packet_length        min_packet_length          1.0
packet_length_mean       packet_length_mean         1.0
packet_length_std        packet_length_std          1.0
dtype: float64

In [44]:
df = df.drop(columns=["fwd_psh_flags"])

In [45]:
print(df.shape)

(97548, 28)

In [46]:
print(df.columns.tolist())

['label', 'dst_port', 'flow_duration', 'total_fwd_packets', 'total_bwd_packets', 'total_len_fwd', 'total_len_bwd', 'flow_packets_s', 'fwd_packets_s', 'bwd_packets_s', 'fwd_packet_length_mean', 'bwd_packet_length_mean', 'min_packet_length', 'max_packet_length', 'packet_length_mean', 'packet_length_std', 'syn_flag_count', 'ack_flag_count', 'rst_flag_count', 'psh_flag_count', 'fin_flag_count', 'down_up_ratio', 'init_win_bytes_forward', 'init_win_bytes_backward', 'active_mean', 'idle_mean', 'incident_id', 'incident_text']

In [47]:
df = df.drop(columns=["incident_id", "incident_text"])

print(df.columns.tolist())
print(df.shape)

['label', 'dst_port', 'flow_duration', 'total_fwd_packets', 'total_bwd_packets', 'total_len_fwd', 'total_len_bwd', 'flow_packets_s', 'fwd_packets_s', 'bwd_packets_s', 'fwd_packet_length_mean', 'bwd_packet_length_mean', 'min_packet_length', 'max_packet_length', 'packet_length_mean', 'packet_length_std', 'syn_flag_count', 'ack_flag_count', 'rst_flag_count', 'psh_flag_count', 'fin_flag_count', 'down_up_ratio', 'init_win_bytes_forward', 'init_win_bytes_backward', 'active_mean', 'idle_mean']
(97548, 26)

In [48]:
output_path = PROJECT_ROOT / "data" / "cleaned_network_data" / "cleaned_network_data.csv"
output_path.parent.mkdir(parents=True, exist_ok=True)

df.to_csv(
    output_path,
    index=False
)

print("Saved successfully!")

Saved successfully!